# Generated by Django 2.2 on 2019-05-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='meeting',
            new_name='meetingtitle',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meetingid',
        ),
    ]
