# Generated by Django 2.0.13 on 2019-06-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='releasedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
